/// All teams data for onboarding and search
class TeamsData {
  static const List<TeamInfo> allTeams = [
    // ===== NFL Teams (32) =====
    TeamInfo(name: 'Kansas City Chiefs', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png'),
    TeamInfo(name: 'San Francisco 49ers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png'),
    TeamInfo(name: 'Philadelphia Eagles', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png'),
    TeamInfo(name: 'Dallas Cowboys', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png'),
    TeamInfo(name: 'Buffalo Bills', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png'),
    TeamInfo(name: 'Miami Dolphins', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png'),
    TeamInfo(name: 'Baltimore Ravens', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png'),
    TeamInfo(name: 'Detroit Lions', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png'),
    TeamInfo(name: 'Green Bay Packers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png'),
    TeamInfo(name: 'Chicago Bears', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png'),
    TeamInfo(name: 'New York Giants', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png'),
    TeamInfo(name: 'New York Jets', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png'),
    TeamInfo(name: 'New England Patriots', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png'),
    TeamInfo(name: 'Denver Broncos', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png'),
    TeamInfo(name: 'Las Vegas Raiders', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png'),
    TeamInfo(name: 'Los Angeles Rams', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png'),
    TeamInfo(name: 'Los Angeles Chargers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png'),
    TeamInfo(name: 'Seattle Seahawks', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png'),
    TeamInfo(name: 'Arizona Cardinals', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png'),
    TeamInfo(name: 'Minnesota Vikings', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png'),
    TeamInfo(name: 'Cleveland Browns', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png'),
    TeamInfo(name: 'Cincinnati Bengals', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png'),
    TeamInfo(name: 'Pittsburgh Steelers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png'),
    TeamInfo(name: 'Tennessee Titans', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png'),
    TeamInfo(name: 'Indianapolis Colts', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png'),
    TeamInfo(name: 'Jacksonville Jaguars', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png'),
    TeamInfo(name: 'Houston Texans', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png'),
    TeamInfo(name: 'Carolina Panthers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png'),
    TeamInfo(name: 'New Orleans Saints', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png'),
    TeamInfo(name: 'Tampa Bay Buccaneers', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png'),
    TeamInfo(name: 'Atlanta Falcons', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png'),
    TeamInfo(name: 'Washington Commanders', sport: 'NFL', sportKey: 'americanfootball_nfl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png'),

    // ===== NBA Teams (30) =====
    TeamInfo(name: 'Boston Celtics', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png'),
    TeamInfo(name: 'Los Angeles Lakers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png'),
    TeamInfo(name: 'Golden State Warriors', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png'),
    TeamInfo(name: 'Denver Nuggets', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png'),
    TeamInfo(name: 'Milwaukee Bucks', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png'),
    TeamInfo(name: 'Phoenix Suns', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png'),
    TeamInfo(name: 'Miami Heat', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png'),
    TeamInfo(name: 'New York Knicks', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/ny.png'),
    TeamInfo(name: 'Philadelphia 76ers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png'),
    TeamInfo(name: 'Los Angeles Clippers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png'),
    TeamInfo(name: 'Brooklyn Nets', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png'),
    TeamInfo(name: 'Chicago Bulls', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png'),
    TeamInfo(name: 'Dallas Mavericks', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png'),
    TeamInfo(name: 'Houston Rockets', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png'),
    TeamInfo(name: 'Cleveland Cavaliers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png'),
    TeamInfo(name: 'Sacramento Kings', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png'),
    TeamInfo(name: 'Atlanta Hawks', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png'),
    TeamInfo(name: 'Memphis Grizzlies', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png'),
    TeamInfo(name: 'Minnesota Timberwolves', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png'),
    TeamInfo(name: 'New Orleans Pelicans', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png'),
    TeamInfo(name: 'Oklahoma City Thunder', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png'),
    TeamInfo(name: 'Indiana Pacers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png'),
    TeamInfo(name: 'Orlando Magic', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png'),
    TeamInfo(name: 'Toronto Raptors', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png'),
    TeamInfo(name: 'Portland Trail Blazers', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png'),
    TeamInfo(name: 'Utah Jazz', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png'),
    TeamInfo(name: 'San Antonio Spurs', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png'),
    TeamInfo(name: 'Charlotte Hornets', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png'),
    TeamInfo(name: 'Detroit Pistons', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png'),
    TeamInfo(name: 'Washington Wizards', sport: 'NBA', sportKey: 'basketball_nba', logoUrl: 'https://a.espncdn.com/i/teamlogos/nba/500/wsh.png'),

    // ===== NHL Teams (32) =====
    TeamInfo(name: 'Edmonton Oilers', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/edm.png'),
    TeamInfo(name: 'Florida Panthers', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/fla.png'),
    TeamInfo(name: 'Vegas Golden Knights', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/vgk.png'),
    TeamInfo(name: 'Colorado Avalanche', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/col.png'),
    TeamInfo(name: 'Dallas Stars', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/dal.png'),
    TeamInfo(name: 'Carolina Hurricanes', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/car.png'),
    TeamInfo(name: 'New York Rangers', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png'),
    TeamInfo(name: 'Boston Bruins', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/bos.png'),
    TeamInfo(name: 'Toronto Maple Leafs', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/tor.png'),
    TeamInfo(name: 'Tampa Bay Lightning', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/tb.png'),
    TeamInfo(name: 'New Jersey Devils', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nj.png'),
    TeamInfo(name: 'Winnipeg Jets', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/wpg.png'),
    TeamInfo(name: 'Los Angeles Kings', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/la.png'),
    TeamInfo(name: 'Vancouver Canucks', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/van.png'),
    TeamInfo(name: 'Pittsburgh Penguins', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/pit.png'),
    TeamInfo(name: 'Washington Capitals', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/wsh.png'),
    TeamInfo(name: 'Detroit Red Wings', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/det.png'),
    TeamInfo(name: 'Minnesota Wild', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/min.png'),
    TeamInfo(name: 'Nashville Predators', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nsh.png'),
    TeamInfo(name: 'St. Louis Blues', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/stl.png'),
    TeamInfo(name: 'Calgary Flames', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/cgy.png'),
    TeamInfo(name: 'Seattle Kraken', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/sea.png'),
    TeamInfo(name: 'New York Islanders', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/nyi.png'),
    TeamInfo(name: 'Philadelphia Flyers', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/phi.png'),
    TeamInfo(name: 'Buffalo Sabres', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/buf.png'),
    TeamInfo(name: 'Ottawa Senators', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/ott.png'),
    TeamInfo(name: 'Montreal Canadiens', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/mtl.png'),
    TeamInfo(name: 'Utah Hockey Club', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/uta.png'),
    TeamInfo(name: 'Anaheim Ducks', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/ana.png'),
    TeamInfo(name: 'San Jose Sharks', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/sj.png'),
    TeamInfo(name: 'Columbus Blue Jackets', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/cbj.png'),
    TeamInfo(name: 'Chicago Blackhawks', sport: 'NHL', sportKey: 'icehockey_nhl', logoUrl: 'https://a.espncdn.com/i/teamlogos/nhl/500/chi.png'),

    // ===== MLB Teams (30) =====
    TeamInfo(name: 'Los Angeles Dodgers', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/lad.png'),
    TeamInfo(name: 'New York Yankees', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png'),
    TeamInfo(name: 'Atlanta Braves', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/atl.png'),
    TeamInfo(name: 'Houston Astros', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/hou.png'),
    TeamInfo(name: 'Philadelphia Phillies', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/phi.png'),
    TeamInfo(name: 'Texas Rangers', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tex.png'),
    TeamInfo(name: 'San Diego Padres', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sd.png'),
    TeamInfo(name: 'Baltimore Orioles', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/bal.png'),
    TeamInfo(name: 'Tampa Bay Rays', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tb.png'),
    TeamInfo(name: 'Minnesota Twins', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/min.png'),
    TeamInfo(name: 'Seattle Mariners', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sea.png'),
    TeamInfo(name: 'Arizona Diamondbacks', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/ari.png'),
    TeamInfo(name: 'Milwaukee Brewers', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/mil.png'),
    TeamInfo(name: 'Toronto Blue Jays', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/tor.png'),
    TeamInfo(name: 'Cleveland Guardians', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/cle.png'),
    TeamInfo(name: 'Boston Red Sox', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/bos.png'),
    TeamInfo(name: 'New York Mets', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/nym.png'),
    TeamInfo(name: 'San Francisco Giants', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/sf.png'),
    TeamInfo(name: 'St. Louis Cardinals', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/stl.png'),
    TeamInfo(name: 'Chicago Cubs', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/chc.png'),
    TeamInfo(name: 'Detroit Tigers', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/det.png'),
    TeamInfo(name: 'Cincinnati Reds', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/cin.png'),
    TeamInfo(name: 'Pittsburgh Pirates', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/pit.png'),
    TeamInfo(name: 'Chicago White Sox', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/chw.png'),
    TeamInfo(name: 'Kansas City Royals', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/kc.png'),
    TeamInfo(name: 'Los Angeles Angels', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/laa.png'),
    TeamInfo(name: 'Miami Marlins', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/mia.png'),
    TeamInfo(name: 'Washington Nationals', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png'),
    TeamInfo(name: 'Colorado Rockies', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/col.png'),
    TeamInfo(name: 'Oakland Athletics', sport: 'MLB', sportKey: 'baseball_mlb', logoUrl: 'https://a.espncdn.com/i/teamlogos/mlb/500/oak.png'),

    // ===== College Basketball (NCAAB) - Major Conference Teams =====
    // ACC
    TeamInfo(name: 'Duke Blue Devils', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png'),
    TeamInfo(name: 'North Carolina Tar Heels', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png'),
    TeamInfo(name: 'Virginia Cavaliers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png'),
    TeamInfo(name: 'NC State Wolfpack', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png'),
    TeamInfo(name: 'Clemson Tigers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png'),
    TeamInfo(name: 'Florida State Seminoles', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png'),
    TeamInfo(name: 'Miami Hurricanes', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png'),
    TeamInfo(name: 'Syracuse Orange', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png'),
    TeamInfo(name: 'Louisville Cardinals', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png'),
    TeamInfo(name: 'Pittsburgh Panthers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png'),
    TeamInfo(name: 'Wake Forest Demon Deacons', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png'),
    TeamInfo(name: 'Notre Dame Fighting Irish', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png'),
    TeamInfo(name: 'Virginia Tech Hokies', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png'),
    TeamInfo(name: 'Georgia Tech Yellow Jackets', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png'),
    TeamInfo(name: 'Boston College Eagles', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png'),
    // Big Ten
    TeamInfo(name: 'Purdue Boilermakers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png'),
    TeamInfo(name: 'Michigan Wolverines', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png'),
    TeamInfo(name: 'Michigan State Spartans', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png'),
    TeamInfo(name: 'Indiana Hoosiers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png'),
    TeamInfo(name: 'Ohio State Buckeyes', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png'),
    TeamInfo(name: 'Illinois Fighting Illini', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png'),
    TeamInfo(name: 'Wisconsin Badgers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png'),
    TeamInfo(name: 'Iowa Hawkeyes', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png'),
    TeamInfo(name: 'Maryland Terrapins', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png'),
    TeamInfo(name: 'Penn State Nittany Lions', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png'),
    TeamInfo(name: 'Rutgers Scarlet Knights', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png'),
    TeamInfo(name: 'Minnesota Golden Gophers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png'),
    TeamInfo(name: 'Northwestern Wildcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png'),
    TeamInfo(name: 'Nebraska Cornhuskers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png'),
    TeamInfo(name: 'UCLA Bruins', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png'),
    TeamInfo(name: 'USC Trojans', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png'),
    TeamInfo(name: 'Oregon Ducks', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png'),
    TeamInfo(name: 'Washington Huskies', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png'),
    // Big 12
    TeamInfo(name: 'Kansas Jayhawks', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png'),
    TeamInfo(name: 'Houston Cougars', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png'),
    TeamInfo(name: 'Baylor Bears', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png'),
    TeamInfo(name: 'Texas Longhorns', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png'),
    TeamInfo(name: 'Texas Tech Red Raiders', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png'),
    TeamInfo(name: 'TCU Horned Frogs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png'),
    TeamInfo(name: 'Iowa State Cyclones', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png'),
    TeamInfo(name: 'Kansas State Wildcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png'),
    TeamInfo(name: 'Oklahoma State Cowboys', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png'),
    TeamInfo(name: 'West Virginia Mountaineers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png'),
    TeamInfo(name: 'BYU Cougars', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png'),
    TeamInfo(name: 'Cincinnati Bearcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png'),
    TeamInfo(name: 'UCF Knights', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png'),
    TeamInfo(name: 'Colorado Buffaloes', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png'),
    TeamInfo(name: 'Arizona Wildcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png'),
    TeamInfo(name: 'Arizona State Sun Devils', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png'),
    TeamInfo(name: 'Utah Utes', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png'),
    // SEC
    TeamInfo(name: 'Kentucky Wildcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png'),
    TeamInfo(name: 'Tennessee Volunteers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png'),
    TeamInfo(name: 'Auburn Tigers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png'),
    TeamInfo(name: 'Alabama Crimson Tide', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png'),
    TeamInfo(name: 'Arkansas Razorbacks', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png'),
    TeamInfo(name: 'LSU Tigers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png'),
    TeamInfo(name: 'Florida Gators', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png'),
    TeamInfo(name: 'Georgia Bulldogs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png'),
    TeamInfo(name: 'South Carolina Gamecocks', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png'),
    TeamInfo(name: 'Missouri Tigers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png'),
    TeamInfo(name: 'Ole Miss Rebels', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png'),
    TeamInfo(name: 'Mississippi State Bulldogs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png'),
    TeamInfo(name: 'Vanderbilt Commodores', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png'),
    TeamInfo(name: 'Texas A&M Aggies', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png'),
    TeamInfo(name: 'Oklahoma Sooners', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png'),
    // Big East
    TeamInfo(name: 'UConn Huskies', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png'),
    TeamInfo(name: 'Villanova Wildcats', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/222.png'),
    TeamInfo(name: 'Creighton Bluejays', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/156.png'),
    TeamInfo(name: 'Marquette Golden Eagles', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/269.png'),
    TeamInfo(name: 'Xavier Musketeers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png'),
    TeamInfo(name: 'Providence Friars', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png'),
    TeamInfo(name: 'Seton Hall Pirates', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png'),
    TeamInfo(name: 'St. Johns Red Storm', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png'),
    TeamInfo(name: 'Butler Bulldogs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png'),
    TeamInfo(name: 'Georgetown Hoyas', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/46.png'),
    TeamInfo(name: 'DePaul Blue Demons', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/305.png'),
    // Other Notable
    TeamInfo(name: 'Gonzaga Bulldogs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png'),
    TeamInfo(name: 'Memphis Tigers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png'),
    TeamInfo(name: 'San Diego State Aztecs', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png'),
    TeamInfo(name: 'Saint Marys Gaels', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png'),
    TeamInfo(name: 'Dayton Flyers', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png'),
    TeamInfo(name: 'VCU Rams', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png'),
    TeamInfo(name: 'Nevada Wolf Pack', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png'),
    TeamInfo(name: 'New Mexico Lobos', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png'),
    TeamInfo(name: 'Boise State Broncos', sport: 'CBB', sportKey: 'basketball_ncaab', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png'),

    // ===== College Football (NCAAF) - Major Conference Teams =====
    // SEC
    TeamInfo(name: 'Georgia Bulldogs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png'),
    TeamInfo(name: 'Alabama Crimson Tide', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png'),
    TeamInfo(name: 'LSU Tigers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png'),
    TeamInfo(name: 'Tennessee Volunteers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png'),
    TeamInfo(name: 'Florida Gators', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png'),
    TeamInfo(name: 'Auburn Tigers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png'),
    TeamInfo(name: 'Texas A&M Aggies', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png'),
    TeamInfo(name: 'Ole Miss Rebels', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png'),
    TeamInfo(name: 'Missouri Tigers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png'),
    TeamInfo(name: 'Kentucky Wildcats', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png'),
    TeamInfo(name: 'South Carolina Gamecocks', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png'),
    TeamInfo(name: 'Arkansas Razorbacks', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png'),
    TeamInfo(name: 'Mississippi State Bulldogs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png'),
    TeamInfo(name: 'Vanderbilt Commodores', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png'),
    TeamInfo(name: 'Texas Longhorns', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png'),
    TeamInfo(name: 'Oklahoma Sooners', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png'),
    // Big Ten
    TeamInfo(name: 'Michigan Wolverines', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png'),
    TeamInfo(name: 'Ohio State Buckeyes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png'),
    TeamInfo(name: 'Penn State Nittany Lions', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png'),
    TeamInfo(name: 'Wisconsin Badgers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png'),
    TeamInfo(name: 'Iowa Hawkeyes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png'),
    TeamInfo(name: 'Michigan State Spartans', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png'),
    TeamInfo(name: 'Minnesota Golden Gophers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png'),
    TeamInfo(name: 'Nebraska Cornhuskers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png'),
    TeamInfo(name: 'Illinois Fighting Illini', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png'),
    TeamInfo(name: 'Purdue Boilermakers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png'),
    TeamInfo(name: 'Indiana Hoosiers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png'),
    TeamInfo(name: 'Northwestern Wildcats', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png'),
    TeamInfo(name: 'Maryland Terrapins', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png'),
    TeamInfo(name: 'Rutgers Scarlet Knights', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png'),
    TeamInfo(name: 'USC Trojans', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png'),
    TeamInfo(name: 'UCLA Bruins', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png'),
    TeamInfo(name: 'Oregon Ducks', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png'),
    TeamInfo(name: 'Washington Huskies', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png'),
    // ACC
    TeamInfo(name: 'Florida State Seminoles', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png'),
    TeamInfo(name: 'Clemson Tigers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png'),
    TeamInfo(name: 'Miami Hurricanes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png'),
    TeamInfo(name: 'North Carolina Tar Heels', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png'),
    TeamInfo(name: 'NC State Wolfpack', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png'),
    TeamInfo(name: 'Louisville Cardinals', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png'),
    TeamInfo(name: 'Pittsburgh Panthers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png'),
    TeamInfo(name: 'Syracuse Orange', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png'),
    TeamInfo(name: 'Duke Blue Devils', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png'),
    TeamInfo(name: 'Virginia Cavaliers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png'),
    TeamInfo(name: 'Virginia Tech Hokies', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png'),
    TeamInfo(name: 'Wake Forest Demon Deacons', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png'),
    TeamInfo(name: 'Georgia Tech Yellow Jackets', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png'),
    TeamInfo(name: 'Boston College Eagles', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png'),
    TeamInfo(name: 'Notre Dame Fighting Irish', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png'),
    TeamInfo(name: 'SMU Mustangs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png'),
    TeamInfo(name: 'Stanford Cardinal', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png'),
    TeamInfo(name: 'California Golden Bears', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png'),
    // Big 12
    TeamInfo(name: 'Kansas State Wildcats', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png'),
    TeamInfo(name: 'Kansas Jayhawks', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png'),
    TeamInfo(name: 'Oklahoma State Cowboys', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png'),
    TeamInfo(name: 'Texas Tech Red Raiders', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png'),
    TeamInfo(name: 'TCU Horned Frogs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png'),
    TeamInfo(name: 'Baylor Bears', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png'),
    TeamInfo(name: 'Iowa State Cyclones', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png'),
    TeamInfo(name: 'West Virginia Mountaineers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png'),
    TeamInfo(name: 'UCF Knights', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png'),
    TeamInfo(name: 'BYU Cougars', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png'),
    TeamInfo(name: 'Cincinnati Bearcats', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png'),
    TeamInfo(name: 'Houston Cougars', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png'),
    TeamInfo(name: 'Colorado Buffaloes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png'),
    TeamInfo(name: 'Arizona Wildcats', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png'),
    TeamInfo(name: 'Arizona State Sun Devils', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png'),
    TeamInfo(name: 'Utah Utes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png'),
    // Other Notable
    TeamInfo(name: 'Oregon State Beavers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png'),
    TeamInfo(name: 'Washington State Cougars', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png'),
    TeamInfo(name: 'Boise State Broncos', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png'),
    TeamInfo(name: 'Memphis Tigers', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png'),
    TeamInfo(name: 'Tulane Green Wave', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png'),
    TeamInfo(name: 'Liberty Flames', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png'),
    TeamInfo(name: 'James Madison Dukes', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png'),
    TeamInfo(name: 'Fresno State Bulldogs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png'),
    TeamInfo(name: 'San Diego State Aztecs', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png'),
    TeamInfo(name: 'UNLV Rebels', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png'),
    TeamInfo(name: 'Air Force Falcons', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png'),
    TeamInfo(name: 'Army Black Knights', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png'),
    TeamInfo(name: 'Navy Midshipmen', sport: 'CFB', sportKey: 'americanfootball_ncaaf', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png'),

    // ===== Soccer - All Leagues Combined (No Duplicates) =====
    // Premier League
    TeamInfo(name: 'Manchester City', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png'),
    TeamInfo(name: 'Arsenal', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png'),
    TeamInfo(name: 'Liverpool', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png'),
    TeamInfo(name: 'Manchester United', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png'),
    TeamInfo(name: 'Chelsea', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png'),
    TeamInfo(name: 'Tottenham Hotspur', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/367.png'),
    TeamInfo(name: 'Newcastle United', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png'),
    TeamInfo(name: 'Aston Villa', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png'),
    TeamInfo(name: 'West Ham United', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/371.png'),
    TeamInfo(name: 'Brighton', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/331.png'),
    TeamInfo(name: 'Wolverhampton', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/380.png'),
    TeamInfo(name: 'Crystal Palace', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png'),
    TeamInfo(name: 'Fulham', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png'),
    TeamInfo(name: 'Everton', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png'),
    TeamInfo(name: 'Brentford', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png'),
    TeamInfo(name: 'Nottingham Forest', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/393.png'),
    TeamInfo(name: 'Bournemouth', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png'),
    TeamInfo(name: 'Leicester City', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/375.png'),
    TeamInfo(name: 'Ipswich Town', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/373.png'),
    TeamInfo(name: 'Southampton', sport: 'Soccer', sportKey: 'soccer_epl', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/376.png'),
    // La Liga
    TeamInfo(name: 'Real Madrid', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png'),
    TeamInfo(name: 'Barcelona', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png'),
    TeamInfo(name: 'Atletico Madrid', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/1068.png'),
    TeamInfo(name: 'Sevilla', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/243.png'),
    TeamInfo(name: 'Real Sociedad', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/89.png'),
    TeamInfo(name: 'Real Betis', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/244.png'),
    TeamInfo(name: 'Villarreal', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/102.png'),
    TeamInfo(name: 'Athletic Bilbao', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/93.png'),
    TeamInfo(name: 'Valencia', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/94.png'),
    TeamInfo(name: 'Girona', sport: 'Soccer', sportKey: 'soccer_spain_la_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9812.png'),
    // Serie A
    TeamInfo(name: 'Inter Milan', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/110.png'),
    TeamInfo(name: 'AC Milan', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/103.png'),
    TeamInfo(name: 'Juventus', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/111.png'),
    TeamInfo(name: 'Napoli', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/114.png'),
    TeamInfo(name: 'Roma', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/104.png'),
    TeamInfo(name: 'Lazio', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/105.png'),
    TeamInfo(name: 'Atalanta', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/107.png'),
    TeamInfo(name: 'Fiorentina', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/109.png'),
    TeamInfo(name: 'Bologna', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/108.png'),
    TeamInfo(name: 'Torino', sport: 'Soccer', sportKey: 'soccer_italy_serie_a', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/239.png'),
    // Bundesliga
    TeamInfo(name: 'Bayern Munich', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png'),
    TeamInfo(name: 'Borussia Dortmund', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png'),
    TeamInfo(name: 'RB Leipzig', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/11420.png'),
    TeamInfo(name: 'Bayer Leverkusen', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/131.png'),
    TeamInfo(name: 'Eintracht Frankfurt', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/125.png'),
    TeamInfo(name: 'VfB Stuttgart', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/134.png'),
    TeamInfo(name: 'Wolfsburg', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/135.png'),
    TeamInfo(name: 'Borussia Monchengladbach', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/137.png'),
    TeamInfo(name: 'Hoffenheim', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/3261.png'),
    TeamInfo(name: 'SC Freiburg', sport: 'Soccer', sportKey: 'soccer_germany_bundesliga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/138.png'),
    // Ligue 1
    TeamInfo(name: 'Paris Saint-Germain', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png'),
    TeamInfo(name: 'Monaco', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/174.png'),
    TeamInfo(name: 'Marseille', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/176.png'),
    TeamInfo(name: 'Lyon', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/167.png'),
    TeamInfo(name: 'Lille', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/166.png'),
    TeamInfo(name: 'Nice', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png'),
    TeamInfo(name: 'Lens', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/169.png'),
    TeamInfo(name: 'Rennes', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/177.png'),
    TeamInfo(name: 'Strasbourg', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/180.png'),
    TeamInfo(name: 'Montpellier', sport: 'Soccer', sportKey: 'soccer_france_ligue_one', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/175.png'),
    // Portuguese
    TeamInfo(name: 'Benfica', sport: 'Soccer', sportKey: 'soccer_portugal_primeira_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/1903.png'),
    TeamInfo(name: 'Porto', sport: 'Soccer', sportKey: 'soccer_portugal_primeira_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/1906.png'),
    TeamInfo(name: 'Sporting CP', sport: 'Soccer', sportKey: 'soccer_portugal_primeira_liga', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/1907.png'),
    // Dutch
    TeamInfo(name: 'Ajax', sport: 'Soccer', sportKey: 'soccer_netherlands_eredivisie', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/139.png'),
    TeamInfo(name: 'PSV Eindhoven', sport: 'Soccer', sportKey: 'soccer_netherlands_eredivisie', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/148.png'),
    TeamInfo(name: 'Feyenoord', sport: 'Soccer', sportKey: 'soccer_netherlands_eredivisie', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/143.png'),
    // MLS
    TeamInfo(name: 'Inter Miami', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'LA Galaxy', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'LAFC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/17362.png'),
    TeamInfo(name: 'Columbus Crew', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/454.png'),
    TeamInfo(name: 'FC Cincinnati', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9854.png'),
    TeamInfo(name: 'Philadelphia Union', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/5513.png'),
    TeamInfo(name: 'Atlanta United', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9345.png'),
    TeamInfo(name: 'Seattle Sounders', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png'),
    TeamInfo(name: 'Portland Timbers', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9498.png'),
    TeamInfo(name: 'New York Red Bulls', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/399.png'),
    TeamInfo(name: 'NYCFC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Sporting Kansas City', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/457.png'),
    TeamInfo(name: 'Austin FC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9919.png'),
    TeamInfo(name: 'Nashville SC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Orlando City', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/6901.png'),
    TeamInfo(name: 'CF Montreal', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Toronto FC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Vancouver Whitecaps', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Houston Dynamo', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'FC Dallas', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Real Salt Lake', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Colorado Rapids', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Minnesota United', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'San Jose Earthquakes', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Chicago Fire', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'DC United', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'New England Revolution', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'Charlotte FC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
    TeamInfo(name: 'St. Louis City SC', sport: 'Soccer', sportKey: 'soccer_usa_mls', logoUrl: 'https://a.espncdn.com/i/teamlogos/soccer/500/9668.png'),
  ];

  /// Get all unique sports
  static List<String> get allSports {
    final sports = allTeams.map((t) => t.sport).toSet().toList();
    // Custom sort order
    final order = ['NFL', 'NBA', 'NHL', 'MLB', 'CBB', 'CFB', 'Soccer'];
    sports.sort((a, b) {
      final aIndex = order.indexOf(a);
      final bIndex = order.indexOf(b);
      if (aIndex == -1 && bIndex == -1) return a.compareTo(b);
      if (aIndex == -1) return 1;
      if (bIndex == -1) return -1;
      return aIndex.compareTo(bIndex);
    });
    return sports;
  }

  /// Get teams for a specific sport
  static List<TeamInfo> getTeamsForSport(String sport) {
    return allTeams.where((t) => t.sport == sport).toList();
  }

  /// Search teams by name
  static List<TeamInfo> searchTeams(String query) {
    if (query.isEmpty) return allTeams;
    final lowerQuery = query.toLowerCase();
    return allTeams.where((t) =>
      t.name.toLowerCase().contains(lowerQuery) ||
      t.sport.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  /// Get team by name
  static TeamInfo? getTeamByName(String name) {
    try {
      return allTeams.firstWhere(
        (t) => t.name.toLowerCase() == name.toLowerCase(),
      );
    } catch (_) {
      return null;
    }
  }

  /// Get total team count
  static int get totalTeams => allTeams.length;
}

class TeamInfo {
  final String name;
  final String sport;
  final String sportKey;
  final String logoUrl;

  const TeamInfo({
    required this.name,
    required this.sport,
    required this.sportKey,
    required this.logoUrl,
  });

  Map<String, dynamic> toJson() => {
    'name': name,
    'sport': sport,
    'sportKey': sportKey,
    'logoUrl': logoUrl,
  };

  factory TeamInfo.fromJson(Map<String, dynamic> json) => TeamInfo(
    name: json['name'] as String,
    sport: json['sport'] as String,
    sportKey: json['sportKey'] as String,
    logoUrl: json['logoUrl'] as String,
  );
}
